/* Untyped file generated by genType. */

import * as ReasonFunctionsBS from './ReasonFunctions.bs';

export const getUser = function (Arg1) {
  const result = ReasonFunctionsBS.getUser(Arg1);
  return {id:result[0], name:result[1], isActive:result[2]}
};
